# Generated by Django 5.1.2 on 2024-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0002_patient_address_patient_age_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_health_check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_condition',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
